#Copyright IBM Corp. All Rights Reserved.
#SPDX-License-Identifier: Apache-2.0

noverify = [
    "github.com/grpc-ecosystem/go-grpc-middleware"
]

[[constraint]]
  version = "0.24.4"
  name = "github.com/hyperledger/burrow"

[[constraint]]
  version = "1.4.0"
  name = "github.com/hyperledger/fabric"

[[constraint]]
  version = "1.0.0-alpha5"
  name = "github.com/hyperledger/fabric-sdk-go"

[[constraint]]
  version = "0.0.3"
  name = "github.com/spf13/cobra"

#Constraints from Fabric
[[constraint]]
  revision = "a3b6351eb1ff8e1bfa30b2f55d7e282186ed8fee"
  name = "github.com/onsi/ginkgo"

[[constraint]]
  version = "1.4.2"
  name = "github.com/onsi/gomega"

[[override]]
  version = "=1.3.0"
  name= "github.com/fsouza/go-dockerclient"

[[override]]
  revision = "0c5f8d2b9b23ab8d23529b3effdcf53bb058298c"
  name = "github.com/docker/docker"

[[override]]
  name = "github.com/docker/libnetwork"
  revision = "19279f0492417475b6bfbd0aa529f73e8f178fb5"

[[override]]
  version = "0.8.0"
  name = "github.com/pkg/errors"

[[override]]
  revision = "df60624c1e9b9d2973e889c7a1cff73155da81c4"
  name = "google.golang.org/genproto"

[[override]]
  version = "1.1.0"
  name = "github.com/golang/protobuf"

[[override]]
  revision = "6b78f7a22d950103fb2669aabb969f56d42d283b"
  name = "github.com/hyperledger/fabric-amcl"

[[constraint]]
  version = "1.9.0"
  name = "go.uber.org/zap"

#Fabric 1.4 requires 1.15.0 and Burrow 0.24.4 requires 1.19.0
[[override]]
  version = "1.15.0"
  name = "google.golang.org/grpc"

#Constraints from Burrow
[[override]]
  revision = "505ab145d0a99da450461ae2c1a9f6cd10d1f447"
  name = "golang.org/x/crypto"

[[override]]
  name = "github.com/btcsuite/btcd"
  revision = "ed77733ec07dfc8a513741138419b8d9d3de9d2d"

#Constraints from fabric-sdk-go
[[override]]
  revision = "aafc9e6bc7b7bb53ddaa75a5ef49a17d6e654be5"
  name = "github.com/spf13/viper"

[[override]]
  revision = "7600349dcfe1abd18d72d3a1770870d9800a7801"
  name = "github.com/prometheus/common"

[[override]]
  revision = "ae68e2d4c00fed4943b5f6698d504a5fe083da8a"
  name = "github.com/prometheus/procfs"

[[override]]
  revision = "292b43bbf7cb8d35ddf40f8d5100ef3837cced3f"
  name = "golang.org/x/net"

[prune]
  go-tests = true
  unused-packages = true

  [[prune.project]]
      name = "github.com/onsi/ginkgo"
      unused-packages = false
      non-go = true

  [[prune.project]]
      name = "github.com/onsi/gomega"
      unused-packages = false
      non-go = true
